CREATE TABLE scraping (
	id BIGINT(7) NOT NULL AUTO_INCREMENT, 
	title VARCHAR(200), 
	content VARCHAR(10000),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
	);  

ALTER DATABASE scraping CHARACTER SET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

ALTER TABLE pages CONVERT TO CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

ALTER TABLE pages CHANGE title title VARCHAR(200) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

ALTER TABLE pages CHANGE content content VARCHAR(10000) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;